# Generated by Django 4.0.3 on 2022-03-23 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
